import Head from "next/head";
import { Inter } from "next/font/google";
import Sidebar from "../../components/Sidebar";
import Feed from "../../components/Feed";
import Widgets from "../../components/Widgets";
import CommentModal from "../../components/CommentModal";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ newsResult, randomUsers }) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">
        {/* SideBar */}
        <Sidebar />

        {/* Feed */}
        <Feed />

        {/* widget */}
        <Widgets
          newsResult={newsResult.articles}
          randomUsers={randomUsers.results}
        />
        {/* Modal */}
        <CommentModal />
      </main>
    </div>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/in.json

export async function getServerSideProps() {
  const newsResult = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/in.json"
  ).then((resp) => resp.json());

  // who to follow
  const randomUsers = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((resp) => resp.json());
  return {
    props: {
      newsResult,
      randomUsers,
    },
  };
}
